---
- name: Get IP addresses
  any_errors_fatal: true
  hosts: aero
  remote_user: root

  tasks:
    - name: Get IP addresses
      become: true
      become_user: root
      shell: ip -f inet addr show eth0 | grep inet | awk '{print $2}' | cut -f1 -d'/'
      register: ip_addr
      failed_when: ip_addr.rc != 0
    - debug:
        var: ip_addr.stdout_lines
